// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwdTenoC7I-5tYO0HXs1vVnJpGzkmUmas',
    appId: '1:195176149854:web:2da392417e3eb4795d95cf',
    messagingSenderId: '195176149854',
    projectId: 'fir-5fbdb',
    authDomain: 'fir-5fbdb.firebaseapp.com',
    storageBucket: 'fir-5fbdb.appspot.com',
    measurementId: 'G-FJQBZ3X2YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXsDb5KXK8VhoxM4tYGvgBzUhJ6L7eZGg',
    appId: '1:195176149854:android:5a572ded1803b5555d95cf',
    messagingSenderId: '195176149854',
    projectId: 'fir-5fbdb',
    storageBucket: 'fir-5fbdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCL4s8T9ptxEMI2AOpGzSefhpwKac0lU',
    appId: '1:195176149854:ios:09e2789e875edfab5d95cf',
    messagingSenderId: '195176149854',
    projectId: 'fir-5fbdb',
    storageBucket: 'fir-5fbdb.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );
}
